const smashCharacters = [
  { name: "Mario", image: "https://www.smashbros.com/assets_v2/img/fighter/mario/main.png" },
  { name: "Donkey Kong", image: "https://www.smashbros.com/assets_v2/img/fighter/donkey_kong/main.png" },
  { name: "Link", image: "https://www.smashbros.com/assets_v2/img/fighter/link/main.png" },
  { name: "Samus", image: "https://www.smashbros.com/assets_v2/img/fighter/samus/main.png" },
  { name: "Dark Samus", image: "https://www.smashbros.com/assets_v2/img/fighter/dark_samus/main.png" },
  { name: "Kirby", image: "https://www.smashbros.com/assets_v2/img/fighter/kirby/main.png" },
  { name: "Fox", image: "https://www.smashbros.com/assets_v2/img/fighter/fox/main.png" },
  { name: "Pikachu", image: "https://www.smashbros.com/assets_v2/img/fighter/pikachu/main.png" },
  { name: "Luigi", image: "https://www.smashbros.com/assets_v2/img/fighter/luigi/main.png" },
  { name: "Ness", image: "https://www.smashbros.com/assets_v2/img/fighter/ness/main.png" },
  { name: "Captain Falcon", image: "https://www.smashbros.com/assets_v2/img/fighter/captain_falcon/main.png" },
  { name: "Jigglypuff", image: "https://www.smashbros.com/assets_v2/img/fighter/jigglypuff/main.png" },
  { name: "Peach", image: "https://www.smashbros.com/assets_v2/img/fighter/peach/main.png" },
  { name: "Daisy", image: "https://www.smashbros.com/assets_v2/img/fighter/daisy/main.png" },
  { name: "Bowser", image: "https://www.smashbros.com/assets_v2/img/fighter/bowser/main.png" },
  { name: "Ice Climbers", image: "https://www.smashbros.com/assets_v2/img/fighter/ice_climbers/main.png" },
  { name: "Sheik", image: "https://www.smashbros.com/assets_v2/img/fighter/sheik/main.png" },
  { name: "Zelda", image: "https://www.smashbros.com/assets_v2/img/fighter/zelda/main.png" },
  { name: "Dr. Mario", image: "https://www.smashbros.com/assets_v2/img/fighter/dr_mario/main.png" },
  { name: "Pichu", image: "https://www.smashbros.com/assets_v2/img/fighter/pichu/main.png" },
  { name: "Falco", image: "https://www.smashbros.com/assets_v2/img/fighter/falco/main.png" },
  { name: "Marth", image: "https://www.smashbros.com/assets_v2/img/fighter/marth/main.png" },
  { name: "Lucina", image: "https://www.smashbros.com/assets_v2/img/fighter/lucina/main.png" },
  { name: "Young Link", image: "https://www.smashbros.com/assets_v2/img/fighter/young_link/main.png" },
  { name: "Ganondorf", image: "https://www.smashbros.com/assets_v2/img/fighter/ganondorf/main.png" },
  { name: "Mewtwo", image: "https://www.smashbros.com/assets_v2/img/fighter/mewtwo/main.png" },
  { name: "Roy", image: "https://www.smashbros.com/assets_v2/img/fighter/roy/main.png" },
  { name: "Chrom", image: "https://www.smashbros.com/assets_v2/img/fighter/chrom/main.png" },
  { name: "Mr. Game & Watch", image: "https://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/main.png" },
  { name: "Meta Knight", image: "https://www.smashbros.com/assets_v2/img/fighter/meta_knight/main.png" },
  { name: "Pit", image: "https://www.smashbros.com/assets_v2/img/fighter/pit/main.png" },
  { name: "Dark Pit", image: "https://www.smashbros.com/assets_v2/img/fighter/dark_pit/main.png" },
  { name: "Zero Suit Samus", image: "https://www.smashbros.com/assets_v2/img/fighter/zero_suit_samus/main.png" },
  { name: "Wario", image: "https://www.smashbros.com/assets_v2/img/fighter/wario/main.png" },
  { name: "Snake", image: "https://www.smashbros.com/assets_v2/img/fighter/snake/main.png" },
  { name: "Ike", image: "https://www.smashbros.com/assets_v2/img/fighter/ike/main.png" },
  { name: "Pokémon Trainer", image: "https://www.smashbros.com/assets_v2/img/fighter/pokemon_trainer/main.png" },
  { name: "Diddy Kong", image: "https://www.smashbros.com/assets_v2/img/fighter/diddy_kong/main.png" },
  { name: "Lucas", image: "https://www.smashbros.com/assets_v2/img/fighter/lucas/main.png" },
  { name: "Sonic", image: "https://www.smashbros.com/assets_v2/img/fighter/sonic/main.png" },
  { name: "King Dedede", image: "https://www.smashbros.com/assets_v2/img/fighter/king_dedede/main.png" },
  { name: "Olimar", image: "https://www.smashbros.com/assets_v2/img/fighter/olimar/main.png" },
  { name: "Lucario", image: "https://www.smashbros.com/assets_v2/img/fighter/lucario/main.png" },
  { name: "R.O.B.", image: "https://www.smashbros.com/assets_v2/img/fighter/rob/main.png" },
  { name: "Toon Link", image: "https://www.smashbros.com/assets_v2/img/fighter/toon_link/main.png" },
  { name: "Wolf", image: "https://www.smashbros.com/assets_v2/img/fighter/wolf/main.png" },
  { name: "Aldeano", image: "https://www.smashbros.com/assets_v2/img/fighter/villager/main.png" },
  { name: "Mega Man", image: "https://www.smashbros.com/assets_v2/img/fighter/mega_man/main.png" },
  { name: "Wii Fit Trainer", image: "https://www.smashbros.com/assets_v2/img/fighter/wii_fit_trainer/main.png" },
  { name: "Rosalina", image: "https://www.smashbros.com/assets_v2/img/fighter/rosalina_and_luma/main.png" },
  { name: "Little Mac", image: "https://www.smashbros.com/assets_v2/img/fighter/little_mac/main.png" },
  { name: "Greninja", image: "https://www.smashbros.com/assets_v2/img/fighter/greninja/main.png" },
  { name: "Palutena", image: "https://www.smashbros.com/assets_v2/img/fighter/palutena/main.png" },
  { name: "PAC-MAN", image: "https://www.smashbros.com/assets_v2/img/fighter/pac_man/main.png" },
  { name: "Robin", image: "https://www.smashbros.com/assets_v2/img/fighter/robin/main.png" },
  { name: "Shulk", image: "https://www.smashbros.com/assets_v2/img/fighter/shulk/main.png" },
  { name: "Bowser Jr.", image: "https://www.smashbros.com/assets_v2/img/fighter/bowser_jr/main.png" },
  { name: "Duck Hunt", image: "https://www.smashbros.com/assets_v2/img/fighter/duck_hunt/main.png" },
  { name: "Ryu", image: "https://www.smashbros.com/assets_v2/img/fighter/ryu/main.png" },
  { name: "Ken", image: "https://www.smashbros.com/assets_v2/img/fighter/ken/main.png" },
  { name: "Cloud", image: "https://www.smashbros.com/assets_v2/img/fighter/cloud/main.png" },
  { name: "Corrin", image: "https://www.smashbros.com/assets_v2/img/fighter/corrin/main.png" },
  { name: "Bayonetta", image: "https://www.smashbros.com/assets_v2/img/fighter/bayonetta/main.png" },
  { name: "Inkling", image: "https://www.smashbros.com/assets_v2/img/fighter/inkling/main.png" },
  { name: "Ridley", image: "https://www.smashbros.com/assets_v2/img/fighter/ridley/main.png" },
  { name: "Simon", image: "https://www.smashbros.com/assets_v2/img/fighter/simon/main.png" },
  { name: "Richter", image: "https://www.smashbros.com/assets_v2/img/fighter/richter/main.png" },
  { name: "King K. Rool", image: "https://www.smashbros.com/assets_v2/img/fighter/king_k_rool/main.png" },
  { name: "Canela", image: "https://www.smashbros.com/assets_v2/img/fighter/isabelle/main.png" },
  { name: "Incineroar", image: "https://www.smashbros.com/assets_v2/img/fighter/incineroar/main.png" },
  { name: "Planta Piraña", image: "https://www.smashbros.com/assets_v2/img/fighter/piranha_plant/main.png" },
  { name: "Joker", image: "https://www.smashbros.com/assets_v2/img/fighter/joker/main.png" },
  { name: "Hero", image: "https://www.smashbros.com/assets_v2/img/fighter/dq_hero/main.png" },
  { name: "Banjo & Kazooie", image: "https://www.smashbros.com/assets_v2/img/fighter/banjo_and_kazooie/main.png" },
  { name: "Terry", image: "https://www.smashbros.com/assets_v2/img/fighter/terry/main.png" },
  { name: "Byleth", image: "https://www.smashbros.com/assets_v2/img/fighter/byleth/main.png" },
  { name: "Min Min", image: "https://www.smashbros.com/assets_v2/img/fighter/minmin/main.png" },
  { name: "Steve", image: "https://www.smashbros.com/assets_v2/img/fighter/steve/main.png" },
  { name: "Sephiroth", image: "https://www.smashbros.com/assets_v2/img/fighter/sephiroth/main.png" },
  { name: "Pyra / Mythra", image: "https://www.smashbros.com/assets_v2/img/fighter/pyra/main.png" },
  { name: "Kazuya", image: "https://www.smashbros.com/assets_v2/img/fighter/kazuya/main.png" },
  { name: "Sora", image: "https://www.smashbros.com/assets_v2/img/fighter/sora/main.png" },
  { name: "Mii Brawler", image: "https://ssb.wiki.gallery/images/thumb/e/e4/Mii_Brawler_SSBU.png/500px-Mii_Brawler_SSBU.png" },
  { name: "Mii Swordfighter", image: "https://ssb.wiki.gallery/images/thumb/f/fa/Mii_Swordfighter_SSBU.png/500px-Mii_Swordfighter_SSBU.png" },
  { name: "Mii Gunner", image: "https://ssb.wiki.gallery/images/thumb/e/e5/Mii_Gunner_SSBU.png/500px-Mii_Gunner_SSBU.png" },
];

export const DEFAULT_PLAYER_COLORS = ["#FFD700", "#FF6B6B", "#4ECDC4", "#9D65C9"];

export const STORAGE_KEY = 'smashGunGameState';

export const DLC_CHARACTER_NAMES = [
  "Planta Piraña", "Joker", "Hero", "Banjo & Kazooie", "Terry", "Byleth",
  "Min Min", "Steve", "Sephiroth", "Pyra / Mythra", "Kazuya", "Sora"
];

export default smashCharacters;